function set_path

%% Adicionando caminhos de busca
addpath('.\Rotinas_Para_Tratar_Dados_Experimentais','.\Rotinas_Ensaios',...
      '.\Resultados_Experimentais\Thais','.\Rotinas_Ajuste_Parametros',...
      '.\Rotinas_Para_Inicializar_variaveis','.\Rotinas_Modelos_Materiais',...
      '.\Resultados_Experimentais\Muller','.\Resultados_Experimentais\Brant\Fluencia_recuperacao',...
      '.\Resultados_Experimentais\Brant\Fluencia', '.\Resultados_Experimentais\Alotta','.\Resultados_Experimentais\Mourad',...
      '.\Resultados_Experimentais\Ensaio_Ficticio','.\Resultados_Experimentais\Ensaio_Ficticio\Ensaio_numerico1','.\Variadas',...
      '.\Resultados_Experimentais\Brant\Ciclico'); 
  
end 